# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Sven Würth"
subtitle: "Home Dashboard"
logo: "assets/icons/SW-Logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> by <a href="https://svenw.de/">Sven Würth</a> and <a href="https://Moritz-Mantel.de/">Moritz Mantel</a> </p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#24d121"
    highlight-secondary: "#24d121"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "DuckDuckGo Search"
  icon: "fas fa-search"
  content: '<iframe src="https://duckduckgo.com/search.html? &focus=yes&kz=1&kac=1&kn=1&kp=-2&k1=-1" style="overflow:hidden;margin:0;padding:0;width:calc(100% - 100px);height:60px;" frameborder="0">'

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/ZigZockt"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additionnal-page.yml and keep default config values as in config.yml file
  # see url field and assets/additionnal-page.yml.dist used in this example:
  - name: "another page!"
    icon: "fas fa-file-alt"
    url: "#additionnal-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Home-Intern"
    icon: "fas fa-network-wired"
    items:
      - name: "Unraid"
        logo: "assets/tools/unraid.png"
        subtitle: "Mein Unraid Server"
        tag: "Gui"
        url: "http://192.168.178.100/"
        target: "_blank" # optional html a tag target attribute
        
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "Meine Nextcloud"
        tag: "Gui"
        url: "http://192.168.178.100:17717/apps/dashboard/"
        target: "_blank"
        
      - name: "Krusader"
        logo: "assets/tools/krusader.png"
        subtitle: "Erst den Docker in UnRAID starten"
        tag: "Gui"
        url: "http://192.168.178.100:8080"
        target: "_blank"
        
      - name: "FRITZ!Box"
        logo: "assets/tools/fritz.png"
        subtitle: "Die Haupt Fritze"
        tag: "Gui"
        url: "http://192.168.178.1/"
        target: "_blank"



  - name: "Server"
    icon: "fas fa-server"
    items:
      - name: "Statuspage"
        logo: "assets/tools/stats.png"
        subtitle: "Uptimerobot - Downdetector"
        tag: "Website"
        url: "https://stats.uptimerobot.com/y5P0zS72wK/"
        target: "_blank" # optional html a tag target attribute
        
      - name: "Svenw.de"
        logo: "assets/tools/website.png"
        subtitle: "Meine Homepage"
        tag: "Website"
        url: "https://svenw.de/"
        target: "_blank" # optional html a tag target attribute
        
      - name: "NASven"
        logo: "assets/tools/cloud.png"
        subtitle: "Nextcloud"
        tag: "Storage"
        url: "https://nas.svenw.de/"
        target: "_blank" # optional html a tag target attribute
   
        
      - name: "Domains-NerdsCave"
        logo: "assets/tools/globe.png"
        subtitle: "Domain Verwaltung"
        tag: "Gui"
        url: "https://my.resellerinterface.de/dashboard"
        target: "_blank" # optional html a tag target attribute
        
      - name: "Webhosting-Minerswin"
        logo: "assets/tools/globe.png"
        subtitle: "Webhosting"
        tag: "Gui"
        url: "https://node03.minerswin-webhosting.de/"
        target: "_blank" # optional html a tag target attribute
        
  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Public IP"
        logo: "assets/tools/network.png"
        subtitle: "What Is My IP?"
        tag: "Tools"
        url: "https://whatismyip.com"
        target: "_blank"
        
      - name: "Whois"
        logo: "assets/tools/search.png"
        subtitle: "Informationen über Domains"
        tag: "Tools"
        url: "https://whois.domaintools.com"
        target: "_blank"
        
      - name: "RIPE Database Query"
        logo: "assets/tools/world.png"
        subtitle: "Informationen über IP Subnetze"
        tag: "Tools"
        url: "https://apps.db.ripe.net/db-web-ui/query?searchtext="
        
      - name: "DNS Lookup"
        logo: "assets/tools/globe.png"
        subtitle: "All DNS Records of Domain"
        tag: "Tools"
        url: "https://dnschecker.org/all-dns-records-of-domain.php"
        target: "_blank"
        
      - name: "CopyChar"
        logo: "assets/tools/checkmark.png"
        subtitle: "find and copy special characters"
        tag: "Tools"
        url: "https://copychar.cc"
        target: "_blank"
        
      - name: "Well-known-ports"
        logo: "assets/tools/ports.png"
        subtitle: "Liste von standardisierten TCP-/ und UDP-Ports"
        tag: "Tools"
        url: "https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports"
        target: "_blank"
        
      - name: "Netzwerkrechner"
        logo: "assets/tools/calc.png"
        subtitle: "Subnets ermitteln"
        tag: "Tools"
        url: "https://www.heise.de/netze/tools/netzwerkrechner/"
        target: "_blank"
        
      - name: "IP Logger"
        logo: "assets/tools/search.png"
        subtitle: "IP Logger whith advanced analytics"
        tag: "Tools"
        url: "https://iplogger.org/"
        target: "_blank"
        
      - name: "ImgOps"
        logo: "assets/tools/tools.png"
        subtitle: "Online Photo Efects"
        tag: "Tools"
        url: "https://imgops.com/"
        target: "_blank"
        
      - name: "Geizhals"
        logo: "assets/tools/tools.png"
        subtitle: "Preisverglech"
        tag: "Tools"
        url: "https://geizhals.de/"
        target: "_blank"
        
      - name: "Shell Befehle"
        logo: "assets/tools/console.png"
        subtitle: "gängige Linux, Mac und Unix Shellbefehle"
        tag: "Tools"
        url: "https://www.shellbefehle.de/"
        target: "_blank"
        
        
  - name: "News"
    icon: "fas fa-newspaper"
    items:
      - name: "Golem"
        logo: "assets/tools/news.png"
        subtitle: "IT-News für Profis"
        tag: "News"
        url: "https://www.golem.de"
        target: "_blank"
        
      - name: "Heise News"
        logo: "assets/tools/news.png"
        subtitle: "heise Online"
        tag: "News"
        url: "https://www.heise.de"
        target: "_blank"

  - name: "Fun"
    icon: "fas fa-grin-tears"
    items:
      - name: "Stupidedia PC"
        logo: "assets/tools/luftnetzgenerator.png"
        subtitle: "Computer Portal for Experts"
        tag: "Portal"
        url: "https://www.stupidedia.org/stupi/Portal:Computer"
        target: "_blank"
        
      - name: "Pr0"
        logo: "assets/tools/Pr0.png"
        subtitle: "Memes"
        tag: "Portal"
        url: "https://pr0gramm.com"
        target: "_blank"
        
  - name: "communication"
    icon: "fas fa-envelope"
    items:
      - name: "Whatsapp"
        logo: "assets/tools/Mailbox.png"
        subtitle: "Whatsapp Messenger"
        tag: "Portal"
        url: "https://web.whatsapp.com"
        target: "_blank"
		
      - name: "Depp-im-net Mailing"
        logo: "assets/tools/Mailbox.png"
        subtitle: "Depp Im Net Webmail"
        tag: "Portal"
        url: "https://webmail.depp-im.net"
        target: "_blank"